language: node_js
node_js: 12

stages:
  - Build
  - Test
  - name: Docs
    if: branch = master

jobs:
  include:
    - stage: 'Docs'
      os: linux
      if: branch = master
      script:
        - '[ -z "${encrypted_4e2fb4889ef8_iv}" ] && exit 0 || true'
        - set -e
        - openssl aes-256-cbc -K $encrypted_4e2fb4889ef8_key -iv $encrypted_4e2fb4889ef8_iv -in .travis.ssh.key.enc -out .travis.ssh.key -d
        - eval "$(ssh-agent -s)"
        - chmod 600 .travis.ssh.key
        - ssh-add .travis.ssh.key
        - yarn
        - yarn run docs
        - rsync -e "ssh -o StrictHostKeyChecking=no" -arv docs/api/ root@ajenti.org:/srv/terminus-docs/
    - stage: Test
      name: DX Scanner
      image: dxheroes/dx-scanner:latest
      script:
        - dx-scanner run --ci

dist: xenial
sudo: false
